import { expect, type Locator, type Page, test } from "@playwright/test";

/**
 * §5 — PanelResizeHandle composes consumer interaction handlers with the
 * library behavior:
 * - cancellable events (pointerdown, keydown, dblclick): consumer first,
 *   `preventDefault()` stops the library behavior;
 * - required events (move/up/cancel/lostpointercapture): consumer first, but
 *   internal handling and cleanup always run, and consumer exceptions
 *   rethrow after cleanup;
 * - the post-drag compatibility click stays suppressed while ordinary
 *   clicks reach the consumer.
 */

const leftWidth = (page: Page) =>
  page
    .locator('[data-resizable-panels-panel-id="left"]')
    .evaluate((element) => element.getBoundingClientRect().width);

const counter = async (events: Locator, name: string) =>
  Number(await events.getAttribute(`data-${name}`));

async function dragHandle(page: Page, dx: number) {
  const handle = page.getByTestId("composed-handle");
  const box = await handle.boundingBox();
  if (!box) throw new Error("Expected composed handle");
  const x = box.x + box.width / 2;
  const y = box.y + box.height / 2;
  await page.mouse.move(x, y);
  await page.mouse.down();
  await page.mouse.move(x + dx, y, { steps: 4 });
  await page.mouse.up();
}

test.describe("handle event composition", () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize({ width: 1200, height: 800 });
  });

  test("consumer handlers observe pointer, capture, and keyboard events", async ({
    page,
  }) => {
    await page.goto("/test/handle-composition");
    const events = page.getByTestId("handle-events");

    await dragHandle(page, 40);
    await expect.poll(() => leftWidth(page)).toBeCloseTo(340, 0);
    expect(await counter(events, "pointerdown")).toBeGreaterThanOrEqual(1);
    expect(await counter(events, "pointermove")).toBeGreaterThanOrEqual(1);
    expect(await counter(events, "pointerup")).toBeGreaterThanOrEqual(1);
    // Releasing the drag releases pointer capture: the consumer's
    // onLostPointerCapture must actually fire (§5 — it used to be silently
    // overwritten by the internal handler).
    await expect
      .poll(() => counter(events, "lostpointercapture"))
      .toBeGreaterThanOrEqual(1);

    const handle = page.getByTestId("composed-handle");
    await handle.focus();
    await page.keyboard.press("ArrowRight");
    await expect.poll(() => leftWidth(page)).toBeCloseTo(350, 0);
    expect(await counter(events, "keydown")).toBeGreaterThanOrEqual(1);
  });

  test("ordinary clicks reach the consumer; the post-drag compatibility click is suppressed", async ({
    page,
  }) => {
    await page.goto("/test/handle-composition");
    const events = page.getByTestId("handle-events");
    const handle = page.getByTestId("composed-handle");

    await handle.click();
    await expect.poll(() => counter(events, "click")).toBe(1);

    await dragHandle(page, 60);
    await expect.poll(() => leftWidth(page)).toBeCloseTo(360, 0);
    // The click generated by releasing the drag never reaches the consumer.
    expect(await counter(events, "click")).toBe(1);

    // A later ordinary click still works.
    await handle.click();
    await expect.poll(() => counter(events, "click")).toBe(2);
  });

  test("preventDefault on pointerdown prevents the drag session", async ({
    page,
  }) => {
    await page.goto("/test/handle-composition?prevent=pointerdown");
    const events = page.getByTestId("handle-events");

    await dragHandle(page, 80);
    await expect
      .poll(() => counter(events, "pointerdown"))
      .toBeGreaterThanOrEqual(1);
    // No session ever started: no width change and no global drag side
    // effects to clean up.
    expect(await leftWidth(page)).toBeCloseTo(300, 0);
    expect(await page.evaluate(() => document.body.style.userSelect)).not.toBe(
      "none",
    );
  });

  test("preventDefault on keydown prevents the keyboard resize", async ({
    page,
  }) => {
    await page.goto("/test/handle-composition?prevent=keydown");
    const events = page.getByTestId("handle-events");
    const handle = page.getByTestId("composed-handle");

    await handle.focus();
    await page.keyboard.press("ArrowRight");
    await expect.poll(() => counter(events, "keydown")).toBe(1);
    expect(await leftWidth(page)).toBeCloseTo(300, 0);
  });

  test("double-click resets by default; preventDefault on dblclick prevents it", async ({
    page,
  }) => {
    await page.goto("/test/handle-composition");
    const events = page.getByTestId("handle-events");
    const handle = page.getByTestId("composed-handle");

    await dragHandle(page, 80);
    await expect.poll(() => leftWidth(page)).toBeCloseTo(380, 0);
    await handle.dblclick();
    await expect
      .poll(() => counter(events, "dblclick"))
      .toBeGreaterThanOrEqual(1);
    await expect.poll(() => leftWidth(page)).toBeCloseTo(300, 0);

    await page.goto("/test/handle-composition?prevent=dblclick");
    await dragHandle(page, 80);
    await expect.poll(() => leftWidth(page)).toBeCloseTo(380, 0);
    await handle.dblclick();
    await expect
      .poll(() => counter(page.getByTestId("handle-events"), "dblclick"))
      .toBeGreaterThanOrEqual(1);
    expect(await leftWidth(page)).toBeCloseTo(380, 0);
  });

  test("a throwing consumer onPointerUp still cleans up the drag session", async ({
    page,
  }) => {
    await page.goto("/test/handle-composition?throw=pointerup");
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));

    await dragHandle(page, 40);
    await expect.poll(() => leftWidth(page)).toBeCloseTo(340, 0);
    // The consumer exception rethrows after internal cleanup.
    await expect
      .poll(() =>
        errors.some((message) =>
          message.includes("consumer onPointerUp failure"),
        ),
      )
      .toBe(true);
    // Cleanup ran: no lingering global drag side effects...
    expect(await page.evaluate(() => document.body.style.userSelect)).not.toBe(
      "none",
    );
    // ...and the session was released — a following drag works.
    await dragHandle(page, 40);
    await expect.poll(() => leftWidth(page)).toBeCloseTo(380, 0);
  });
});
