import type { ChangelogMetaEntry } from "./schema";

// Generated by scripts/generate-changelog-feeds.ts. Edit the MDX entries instead.
export const generatedChangelogMetadata = [
  {
    "source": "./entries/2026-07-28-v0.1.0.mdx",
    "meta": {
      "slug": "2026-07-first-public-release",
      "version": "0.1.0",
      "date": "2026-07-28",
      "title": "🎉 The first public release",
      "summary": "A headless foundation for building animated, resizable application layouts in React.",
      "draft": false,
      "latest": true
    }
  }
] satisfies ChangelogMetaEntry[];
